apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-node-exporter
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: external-node-exporter

  namespaceSelector:
    matchNames:
      - monitoring

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scheme: http
