grafana:
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi

  ingress:
    enabled: true
    ingressClassName: traefik

    hosts:
      - grafana.lab.local

    path: /
    pathType: Prefix

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi