apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-gateway.fullname" . }}
  labels:
    {{- include "ai-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.tls.secretName }}
    - port: 443
      targetPort: api
      protocol: TCP
      name: https
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.duoWorkflow.enabled }}
    - port: 50052
      targetPort: grpc
      protocol: TCP
      name: grpc
      appProtocol: kubernetes.io/h2c
    {{- end }}
  selector:
    {{- include "ai-gateway.selectorLabels" . | nindent 4 }}
