apiVersion: monitoring.coreos.com/v1
kind: Probe

metadata:
  name: itwo40-probe
  namespace: monitoring

  labels:
    release: prometheus-stack

spec:
  interval: 30s

  module: http_2xx

  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - https://apps.itwo40.eu
``